include:
  - db-service.yml

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.production
    image: "recipe_box.api:latest"
    ports:
      - "8083:80"
    networks:
      - teapothill
    env_file:
      - path: "./config/.bills_galley.env"
        required: true
    depends_on:
     db:
       condition: service_healthy
 
volumes:
  teapothill_volume:
    external: true

networks:
  teapothill:
    external: true